version: '3.8'
services:
  sqlserver:
    container_name: blog-backend
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'password1234321'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
    driver: local
